name: ucomm
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  flutter_riverpod: ^2.5.1
  equatable: ^2.0.5
  flutter_secure_storage: ^9.2.2
  flutter_rating_bar: ^4.0.1
  carousel_slider_plus: ^7.0.1
  smooth_page_indicator: ^1.2.0+3
  responsive_grid_list: ^1.4.0
  flutter_slidable: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/

  # example:
  fonts:
    - family: Monoton
      fonts:
        - asset: assets/fonts/Monoton-Regular.ttf
          weight: 700
    - family: ABeeZee
      fonts:
        - asset: assets/fonts/ABeeZee-Regular.ttf
          weight: 400
    - family: Abel
      fonts:
        - asset: assets/fonts/Abel-Regular.ttf
          weight: 400
    - family: Aclonica
      fonts:
        - asset: assets/fonts/Aclonica-Regular.ttf
          weight: 400
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
    - family: Aksara
      fonts:
        - asset: assets/fonts/Aksara-regular.otf
          weight: 600
    - family: Airbnb
      fonts:
        - asset: assets/fonts/AirbnbCereal_W_Md.otf
          weight: 500
    - family: Grotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
          weight: 700

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
